### ISSUE TITLE
Add AI generation of short texts with the repeated words.

### ISSUE THREAD

**Issue by IAmIrina** [IAmIrina/cause_me_bot#3]
Add AI generation of short texts with the repeated words.
About 13 tokens for one studing word.

**Comment by u7er** [comment]
We can use here generated examples from Reverso Context https://pypi.org/project/Reverso-API/

**Comment by IAmIrina** [comment]
> We can use here generated examples from Reverso Context https://pypi.org/project/Reverso-API

Hello, sorry I didn't see your comment earlier. I think I put the description of the feature not enough correctly. I meant a feature to generate short stories with all words which user should repeat today. For example, a user should repeat two words today: "Hi" and "Altered Carbon", AI generates one story including the both words ""Hi," said the AI in the altered carbon sleeve. "I've been waiting for you to wake up. Our mission to save humanity starts now." 
I just looked into Reverso functionality and I didn't find anything about generation such texts with few linked words.
Thank you for your collaboration.  Any ideas are welcome 🤗
